POST http://localhost:8080/event/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbGxvQGV4YW1wbGUuY29tIiwiZXhwIjoxNzAzNzA1MzM0LCJ1c2VySWQiOjJ9._2PoTn2ddkcSDptZGKinELEv6z_lHyQW1N7-5MBm70w
